Repository KW-AUTA/client, pull requests merged in 2025-06, with the labels that each got.

#64 [ # 58 | fix ] 피그마 파일 업로드 및 서버 통신(프로젝트 생성)
  src/assets/icons/upload.svg
  src/components/ui/input/FileInput.tsx
  src/pages/project/ProjectCreatePage.tsx
  src/pages/project/_components/projectForm/DesignSourceSection.tsx
  src/pages/project/_components/projectForm/ProjectCreateForm.tsx
  src/store/queries/project/useProjectMutations.ts
  src/types/project.type.ts
Labels: enhancement

#65 [ #52 | hotfix ] eslint 수정
  src/pages/project/ProjectCreatePage.tsx
  src/pages/project/_components/projectForm/DesignSourceSection.tsx
  src/store/queries/project/useProjectMutations.ts
Labels: bug

#67 [ #52 | Design ] TutorialPage 리디자인 : 캐레설 구현
  package-lock.json
  package.json
  src/assets/icons/kakaotalk-seeklogo.svg
  src/assets/images/manual1.png
  src/assets/images/manual2.png
  src/assets/images/manual3.png
  src/assets/images/manual4.png
  src/assets/images/manual5.png
  src/assets/images/manual6.png
  src/pages/manual/ManualPage.tsx
  src/pages/manual/ManualPrivatePage.tsx
  src/pages/manual/_components/ManualContent.tsx
Labels: bug, enhancement

#71 [ #69 | Feat ] 캡스톤용 개발 완
  package-lock.json
  package.json
  src/App.tsx
  src/constants/index.ts
  src/pages/main/_components/DashboardProjectTable.tsx
  src/pages/main/_components/DashboardTestTable.tsx
  src/pages/project/ProjectCreatePage.tsx
  src/pages/project/ProjectModifyPage.tsx
  src/pages/project/_components/projectDetail/ProjectControlButtons.tsx
  src/pages/project/_components/projectForm/ProjectCreateForm.tsx
  src/pages/project/_hooks/useCreateProject.ts
  src/pages/test/_components/testDetail/page-issue/IssueContents.tsx
  src/store/queries/test/useTestMutations.ts
  src/types/dashboard.type.ts
  src/types/test.type.ts
Labels: enhancement

#73 Temp fix/72 temp test api
  package-lock.json
  package.json
  src/components/AnimatedBackground.tsx
  src/components/CheckPatternBackground.tsx
  src/pages/auth/LoginPage.tsx
  src/pages/main/LandingPage.tsx
  src/pages/project/ProjectMangePage.tsx
  src/pages/test/TestManagePage.tsx
Labels: enhancement

#78 [ #76 | Style ] 반응형
  src/components/layout/page-layout/Header.tsx
  src/components/layout/page-layout/Layout.tsx
  src/components/layout/sidebar/Sidebar.tsx
  src/components/ui/progressBar/CircleProgressBar.tsx
  src/components/ui/progressBar/LinearProgressBar2.tsx
  src/pages/auth/_components/AuthForm.tsx
  src/pages/project/ProjectCreatePage.tsx
  src/pages/project/ProjectMangePage.tsx
  src/pages/project/ProjectModifyPage.tsx
  src/pages/project/_components/ProjectTitle.tsx
  src/pages/project/_components/projectDetail/ProjectInfo.tsx
  src/pages/project/_components/projectDetail/ProjectInfoItem.tsx
  src/pages/project/_components/projectDetail/ProjectSummaryGraph.tsx
  src/pages/project/_components/projectForm/ProjectCreateForm.tsx
  src/pages/project/_components/responsive_tableListCard/TableListCard.tsx
  src/pages/project/_hooks/useProjectFormHandler.ts
  src/pages/test/_components/TestTitle.tsx
  src/pages/test/_components/searchHeader/SearchHeader.tsx
  src/pages/test/_components/testDetail/TestRatingBars.tsx
  src/pages/test/_components/testList/TestList.tsx
  src/services/api/axios.ts
Labels: enhancement

#80 [ #79 | Refactor ] 깨작깨작 반응형 수정
  src/assets/icons/refresh.svg
  src/components/layout/page-layout/Layout.tsx
  src/pages/auth/_components/AuthForm.tsx
  src/pages/main/DashboardPage.tsx
  src/pages/main/LandingPage.tsx
  src/pages/main/LandingPage_v1.tsx
  src/pages/main/_components/OverviewSection.tsx
  src/pages/manual/_components/ManualContent.tsx
  src/pages/setting/ProfileEditPage.tsx
  src/pages/test/TestManagePage.tsx
  src/pages/test/_components/searchHeader/SearchHeader.tsx
  src/pages/test/_components/testDetail/page-issue/CheckBoxes.tsx
  tailwind.config.ts
Labels: enhancement
