Repository KW-AUTA/client, pull requests merged in 2025-05, with the labels that each got.

#18 [ #17 | Feat ] 공통 컴포넌트 생성
  index.html
  public/assets/fonts/BMDOHYEON_otf.otf
  public/assets/fonts/BMDOHYEON_ttf.ttf
  public/assets/fonts/Pretendard-Bold.woff
  public/assets/fonts/Pretendard-Medium.woff
  public/assets/fonts/Pretendard-Regular.woff
  public/assets/fonts/Pretendard-SemiBold.woff
  public/vite.svg
  src/App.css
  src/App.tsx
  src/assets/icons/dashboard.svg
  src/assets/icons/notification.svg
  src/assets/icons/plus.svg
  src/assets/icons/project.svg
  src/assets/icons/search.svg
  src/assets/icons/setting.svg
  src/assets/icons/test.svg
  src/assets/icons/tutorial.svg
  src/assets/images/no-profile.png
  src/assets/logos/AUTA_big.svg
  src/assets/logos/AUTA_small.svg
  src/assets/react.svg
  src/components/layout/Layout.tsx
  src/components/layout/page-layout/Footer.tsx
  src/components/layout/page-layout/Header.tsx
  src/components/layout/page-layout/Layout.tsx
  src/components/layout/sidebar/Sidebar.tsx
  src/components/layout/sidebar/_components/MenuItem.tsx
  src/components/layout/sidebar/_components/SidebarData.ts
  src/components/ui/button/Button.tsx
  src/components/ui/input/Input.tsx
  src/index.css
  src/main.tsx
  src/pages/main/DashboardPage.tsx
  src/pages/main/LandingPage.tsx
  src/routes/PrivateRoutes.tsx
  src/routes/PublicRoutes.tsx
  src/styles/fonts.css
  src/styles/index.css
  src/styles/theme/colors.ts
  src/styles/theme/shape.ts
  src/styles/theme/theme.ts
  src/styles/theme/typography.ts
  tailwind.config.js
  tailwind.config.ts
  tsconfig.app.json
Labels: enhancement

#20 [ #16 | Feat ] 로그인, 회원가입 페이지 개발
  src/App.tsx
  src/components/layout/page-layout/Layout.tsx
  src/components/layout/sidebar/Sidebar.tsx
  src/components/ui/input/Input.tsx
  src/pages/auth/LoginPage.tsx
  src/pages/auth/SignupPage.tsx
  src/pages/auth/_components/AuthForm.tsx
  src/pages/main/DashboardPage.tsx
  src/pages/main/LandingPage.tsx
  src/routes/PrivateRoutes.tsx
  src/routes/PublicRoutes.tsx
  src/routes/RouteGuard.tsx
  src/routes/index.tsx
  src/services/api/axios.ts
  src/store/api/apiSlice.ts
  src/store/queries/auth/useAuthMutations.ts
  src/store/queries/user/useUserMutations.ts
  src/store/queries/user/useUserQueries.ts
  src/store/redux/reducers/auth.ts
  src/store/redux/store.ts
  src/types/auth.type.ts
  src/types/index.ts
  src/types/user.type.ts
Labels: enhancement

#24 [ #23 | Feat ] setting page, 프로필 수정 페이지 개발
  package-lock.json
  package.json
  src/assets/images/짱구.jpg
  src/components/layout/page-layout/Header.tsx
  src/components/layout/sidebar/_components/MenuItem.tsx
  src/components/layout/sidebar/_components/SidebarData.ts
  src/components/ui/input/Input.tsx
  src/pages/auth/LoginPage.tsx
  src/pages/auth/SignupPage.tsx
  src/pages/auth/_components/AuthForm.tsx
  src/pages/setting/ProfileEditPage.tsx
  src/pages/setting/SettingPage.tsx
  src/pages/setting/_components/ProfileForm.tsx
  src/pages/setting/_components/SettingCard.tsx
  src/pages/setting/_components/SettingCardData.ts
  src/store/queries/auth/useAuthMutations.ts
  src/store/queries/user/useUserMutations.ts
  src/store/queries/user/useUserQueries.ts
  src/styles/theme/shape.ts
  src/types/auth.type.ts
  src/types/user.type.ts
  tailwind.config.ts
Labels: enhancement

#27 [ #26 | Chore ] 버셀 무료 배포를 위한 github action 설정
  .github/workflows/deploy.yml
  build.sh
Labels: chore

#31 [ #30 | Chore ] sidebar 아이콘 이미지 경로 import문으로 변경
  index.html
  src/components/layout/sidebar/_components/SidebarData.ts
Labels: chore

#33 [ #25 | Feat ]project list page 개발
  package-lock.json
  package.json
  src/components/layout/page-layout/Header.tsx
  src/components/layout/sidebar/_components/SidebarData.ts
  src/components/ui/table/CustomTable.tsx
  src/constants/index.ts
  src/pages/auth/LoginPage.tsx
  src/pages/project/ProjectMangePage.tsx
  src/pages/project/_components/ProjectTitle.tsx
  src/pages/project/_components/StatusBadge.tsx
  src/store/queries/auth/useAuthMutations.ts
  src/store/queries/project/useProjectMutations.ts
  src/store/queries/project/useProjectQueries.ts
  src/styles/theme/colors.ts
  src/types/project.type.ts
Labels: enhancement

#36 [ #35 | Fix ] vercel.json 파일 추가
  vercel.json
Labels: bug

#38 [ #34 | Feat ] 토큰 재발급 API 연결
  src/services/api/axios.ts
Labels: enhancement

#44 [ #40 | Feat ] 테스트 관리 페이지 개발
  src/components/layout/sidebar/Sidebar.tsx
  src/components/ui/progressBar/LinearProgressBar.tsx
  src/components/ui/scrollTopButton/ScrollToTopButton.tsx
  src/components/ui/select/Select.tsx
  src/pages/project/ProjectMangePage.tsx
  src/pages/setting/ProfileEditPage.tsx
  src/pages/setting/SettingPage.tsx
  src/pages/setting/_components/SettingTitle.tsx
  src/pages/test/TestManagePage.tsx
  src/pages/test/_components/TestTitle.tsx
  src/pages/test/_components/searchHeader/SearchHeader.tsx
  src/pages/test/_components/testList/TestList.tsx
  src/pages/test/_components/testList/TestListItem.tsx
  src/store/queries/test/useTestMutations.ts
  src/store/queries/test/useTestQueries.ts
  src/styles/theme/colors.ts
  src/types/test.type.ts
  src/utils/useIntersectionObserver.ts
Labels: enhancement

#46 [ #45 | Fix ] 진행률 bar 계산식 수정
  src/components/ui/progressBar/LinearProgressBar.tsx
  src/constants/index.ts
  src/pages/test/TestManagePage.tsx
  src/pages/test/_components/testList/TestList.tsx
  src/pages/test/_components/testList/TestListItem.tsx
  src/services/api/axios.ts
  src/types/test.type.ts
  src/utils/useCalculateTestPercentage.ts
Labels: bug

#50 [ #43 | Feat ] 대시보드 페이지 UI 및 api 연동
  package-lock.json
  package.json
  src/assets/icons/dash-project.svg
  src/assets/icons/dash-projecting.svg
  src/assets/icons/dash-test.svg
  src/components/layout/page-layout/Header.tsx
  src/components/layout/page-layout/Layout.tsx
  src/pages/main/DashboardPage.tsx
  src/pages/main/_components/DashboardProjectTable.tsx
  src/pages/main/_components/DashboardTestTable.tsx
  src/pages/main/_components/OverviewCard.tsx
  src/pages/main/_components/OverviewSection.tsx
  src/store/queries/dashboard/useDashboardHomeQuery.ts
  src/types/dashboard.type.ts
  src/types/svg.d.ts
  tsconfig.app.json
  vite.config.ts
Labels: enhancement
